# Copyright (c) 2015, Stephan Linz <linz@li-pro.net>
# All rights reserved.
#

set test "package"
spawn ./src/mkcg.vid2k
expect {
  -re "^.*\\r\\nPackage: pcmtools\\r\\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "version"
spawn ./src/mkcg.vid2k
expect {
  -re "^.*\\r\\nVersion: 2015-devel\\r\\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "provides"
spawn ./src/mkcg.vid2k
expect {
  -re "^.*\\r\\nPC/M VID2k character generator PROM.*\\r\\n$" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "hexdump-single"
spawn ./src/mkcg.vid2k --hexdump \
      ${srcdir}/data/CG_VID2K/original/ascii_0x30.xpm
expect {
  -re "^0000000: C7 BB B3 AB 9B BB C7 FF FF FF FF FF FF FF FF FF \\r\\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "hexdump-single-negated"
spawn ./src/mkcg.vid2k --neg --hexdump \
      ${srcdir}/data/CG_VID2K/original/ascii_0x30.xpm
expect {
  -re "^.*: invalid option\\r\\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "overview-original-ascii-0x30"
spawn ./src/mkcg.vid2k --quiet --overview=32 \
      ${srcdir}/data/CG_VID2K/original/ascii_0x30.xpm
expect {
  -re "^/\\* XPM \\*/\r\n.*\r\n.*\"256 10 4 1\",\r\n.*\r\n$" {
    pass "$test"
  }
  eof {fail "$test"}
}
