# Copyright (c) 2015, Stephan Linz <linz@li-pro.net>
# All rights reserved.
#

set test "package"
spawn ./src/mkcg.6416
expect {
  -re "Package: pcmtools\r\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "version"
spawn ./src/mkcg.6416
expect {
  -re "Version: 2015-devel\r\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "provides"
spawn ./src/mkcg.6416
expect {
  -re "original PC/M 64x16 character generator PROM" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "hexdump-single"
spawn ./src/mkcg.6416 --hexdump \
      ${srcdir}/data/CG_6416/original/ascii_0x30.xpm
expect {
  -re "^0000000: 38 44 4C 54 64 44 38 00 \r\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "hexdump-single-negated"
spawn ./src/mkcg.6416 --neg --hexdump \
      ${srcdir}/data/CG_6416/original/ascii_0x30.xpm
expect {
  -re "^0000000: C6 BA B2 AA 9A BA C6 FE \r\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "overview-original"
spawn ./src/mkcg.6416 --quiet -o 32 \
      [lsort [glob -dir "${srcdir}/data/CG_6416/original" "*.xpm"]]
expect {
  -re "^\/\* XPM \*\/\r\n" {
    pass "$test"
  }
  eof {fail "$test"}
}
