# Copyright (c) 2015, Stephan Linz <linz@li-pro.net>
# All rights reserved.
#

set test "package"
spawn ./src/mkcg.6416
expect {
  -re "^.*\\r\\nPackage: pcmtools\\r\\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "version"
spawn ./src/mkcg.6416
expect {
  -re "^.*\\r\\nVersion: 2015-devel\\r\\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "provides"
spawn ./src/mkcg.6416
expect {
  -re "^.*\\r\\noriginal PC/M 64x16 character generator PROM.*\\r\\n$" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "hexdump-single"
spawn ./src/mkcg.6416 --hexdump \
      ${srcdir}/data/CG_6416/original/ascii_0x30.xpm
expect {
  -re "^0000000: 38 44 4C 54 64 44 38 00 \\r\\n" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "hexdump-single-negated"
spawn ./src/mkcg.6416 --neg --hexdump \
      ${srcdir}/data/CG_6416/original/ascii_0x30.xpm
expect {
  -re "^0000000: C6 BA B2 AA 9A BA C6 FE \\r\\n$" {
    pass "$test"
  }
  eof {fail "$test"}
}

set test "overview-original-ascii-0x30"
spawn ./src/mkcg.6416 --quiet --overview=32 \
      ${srcdir}/data/CG_6416/original/ascii_0x30.xpm
expect {
  -re "^/\\* XPM \\*/\\r\\n.*\\r\\n.*\"224 8 4 1\",\\r\\n.*\\r\\n$" {
    pass "$test"
  }
  eof {fail "$test"}
}
